---
# Update Package List
- name: Update package lists
  apt: update_cache=yes cache_valid_time={{ settler_cache_valid_time }}
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1

- name: Upgrade all packages
  apt: upgrade=dist
  when: settler_upgrade_packages

# Force US locale
- name: Force locale
  lineinfile: line='LC_ALL=en_US.UTF-8' dest=/etc/default/locale
- name: locale gen
  locale_gen: name=en_US.UTF-8 state=present

# Install Some PPAs
- name: Install software-properties-common
  apt: name={{ item }} state=present
  with_items:
    - "software-properties-common"
    - "curl"

# Add required repositories
- name: Add package repositories
  apt_repository: repo={{ item }}
  with_items:
    - "ppa:nginx/stable"
    - "ppa:chris-lea/redis-server"
    - "ppa:ondrej/php"

# Install basic packages
- name: Install basic packages
  apt: name={{ item }} state=present
  with_items:
    - "build-essential"
    - "dos2unix"
    - "gcc"
    - "git"
    - "libmcrypt4"
    - "libpcre3-dev"
    - "libnotify-bin"
    - "make"
    - "python2.7-dev"
    - "python-pip"
    - "re2c"
    - "supervisor"
    - "unattended-upgrades"
    - "whois"
    - "vim"

# Set timezone
- name: Set timezone
  file: src={{ settler_timezone_file }} dest=/etc/localtime state=link force=yes

# Install PHP
- import_tasks: includes/php.yml
  tags: sysctl-tweaks

# Install Composer
- import_tasks: includes/composer.yml
  tags: composer

# Install nginx
- import_tasks: includes/nginx.yml
  tags: nginx

# Add the user to the web group
- user:
    name: "{{ ansible_user }}"
    groups: www-data

# Add User To www-data
- name: Add user to www-data
  user: name={{ settler_user }} groups=www-data append=yes
  notify:
    - Restart php-fpm
    - Restart nginx

# Set the nginx user to allow writing to public
- file:
    path: "{{ settler_nginx_site_folder_root }}/{{ settler_nginx_site_public_folder }}"
    state: directory
    owner: "{{ settler_user }}"
    group: www-data
    mode: 0770

# Own the web directory
- file:
    path: "{{ settler_nginx_site_folder_root }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"
    group: www-data
    mode: 0770

# Enable Swap Memory
- command: /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024 creates=/var/swap.1
  register: swap
- command: /sbin/mkswap /var/swap.1
  when: swap.changed
- command: /sbin/swapon /var/swap.1
  when: swap.changed

# Tweak sysctl
- import_tasks: includes/sysctl-tweaks.yml
  tags: sysctl-tweaks

# Add SSH Users
- import_tasks: includes/ssh-users.yml
  tags: ssh-users

# Conditional installations
# Install Blackfire
- name: Install blackfire
  apt: name={{ item }} state=present
  with_items:
    - blackfire-agent
    - blackfire-php
  when: settler_blackfire

# Redis
- name: Install redis
  apt: name={{ item }} state=present
  with_items:
    - redis-server
  when: settler_redis

# Memcached
- name: Install memcached
  apt: name={{ item }} state=present
  with_items:
    - memcached
  when: settler_memcached

# Beanstalkd
- import_tasks: includes/beanstalkd.yml
  when: settler_beanstalkd

# Let encrypt
- import_tasks: includes/letsencrypt.yml
  when:
    - settler_letsencrypt == "yes"
    - (not pem.stat.exists) or (force_letsencrypt is defined)
  tags: letsencrypt