---

- name: install Google pagespeed module
  apt: name={{ item }} state=present
  with_items:
    - nginx-module-pagespeed
  notify:
    - restart nginx

- name: turn on pagespeed module
  lineinfile: dest=/etc/nginx/nginx.conf regexp="{{ item.regex }}" line="{{ item.line }}"
  with_items:
    - {regex: "#load_module modules/ngx_pagespeed", line: "load_module modules/ngx_pagespeed.so;"}
  notify:
    - restart nginx

- name: create pagespeed folder
  file:
    owner: nginx
    group: nginx
    mode: 0775
    state: directory
    path: /var/ngx_pagespeed_cache
  notify:
    - restart nginx