---
- name: Restart nginx
  service: name=nginx state=restarted

- name: Restart php-fpm
  command: service php7.2-fpm restart

- name: Restart memcached
  service: name=memcached state=restarted

- name: Restart beanstalkd
  service: name=beanstalkd state=restarted

- name: Restart blackfire-agent
  service: name=blackfire-agent state=restarted

- name: Restart redis-server
  service: name=redis-server state=restarted

- name: Set laravel folder permissions
  file: path="{{ settler_nginx_site_folder_root }}/{{ item }}" recurse=yes owner="{{ settler_user }}" mode=0755 state=directory
  with_items:
    - "public"
    - "storage"
    - "bootstrap/cache"

- name: Reload sysctl
  command: sysctl -p