---
# handlers file for settler
- name: restart nginx
  service: name=nginx state=restarted

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: restart memcached
  service: name=memcached state=restarted

- name: restart beanstalkd
  service: name=beanstalkd state=restarted

- name: restart blackfire-agent
  service: name=blackfire-agent state=restarted

- name: restart redis-server
  service: name=redis-server state=restarted
