---
- name: Check if we need to install letsencrypt
  stat: path="/etc/letsencrypt/live/{{ settler_letsencrypt_domain }}/fullchain.pem"
  register: pem
  tags: letsencrypt
  when: settler_letsencrypt_domain is defined

- name: Install letsencrypt from apt
  apt: name=letsencrypt update_cache=yes
  sudo: yes

- name: Prepare letsencrypt domain proof folder
  file: path="{{ settler_nginx_site_folder_root }}{{ settler_nginx_site_public_folder }}" state=directory owner="{{ settler_user }}" group="{{ settler_user }}"
  sudo: yes

- name: Prepare server for proving domain ownership
  template: src=nginx-default-domain-proof.j2 dest={{ item }}
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default

- name: Boot up server in non-https to prove domain ownership
  service: name=nginx state=restarted

- name: Use letsencrypt webroot plugin
  command: |
    letsencrypt certonly
    -a webroot
    --webroot-path={{ settler_nginx_site_folder_root }}{{ settler_nginx_site_public_folder }}
    -d {{ settler_letsencrypt_domain }}
    --non-interactive
    --agree-tos
    --email {{ settler_letsencrypt_email }}
  sudo: yes
  notify: restart nginx

- name: Reset nginx sites template
  template: src=nginx-default.j2 dest={{ item }}
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default