---
  - name: Add additional public keys
    blockinfile:
      dest: "{{ ssh_auth_keys_file }}"
      block: |
        # {{ item.name }}
        {{ item.key }}
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      state: "{{ item.state|default('present') }}"
    with_items: "{{ ssh_list }}"
    when: add_ssh_users