---
  - name: Tweak sysctl settings
    sysctl: name={{ item.key }} value={{ item.value }} state=present
    with_items:
      - { key: 'fs.file-max', value: '2097152' }
      - { key: 'vm.swappiness', value: '10' }
      - { key: 'vm.dirty_ratio', value: '60' }
      - { key: 'vm.dirty_background_ratio', value: '2' }
      - { key: 'net.ipv4.tcp_synack_retries', value: '2' }
      - { key: 'net.ipv4.ip_local_port_range', value: '2000 65535' }
      - { key: 'net.ipv4.tcp_rfc1337', value: '1' }
      - { key: 'net.ipv4.tcp_fin_timeout', value: '15' }
      - { key: 'net.ipv4.tcp_keepalive_time', value: '300' }
      - { key: 'net.ipv4.tcp_keepalive_probes', value: '5' }
      - { key: 'net.ipv4.tcp_keepalive_intvl', value: '15' }
      - { key: 'net.core.rmem_default', value: '31457280' }
      - { key: 'net.core.rmem_max', value: '12582912' }
      - { key: 'net.core.wmem_default', value: '31457280' }
      - { key: 'net.core.wmem_max', value: '12582912' }
      - { key: 'net.core.somaxconn', value: '4096' }
      - { key: 'net.core.netdev_max_backlog', value: '65536' }
      - { key: 'net.core.optmem_max', value: '25165824' }
      - { key: 'net.ipv4.tcp_mem', value: '65536 131072 262144' }
      - { key: 'net.ipv4.udp_mem', value: '65536 131072 262144' }
      - { key: 'net.ipv4.tcp_rmem', value: '88192 87380 16777216' }
      - { key: 'net.ipv4.udp_rmem_min', value: '16384' }
      - { key: 'net.ipv4.tcp_wmem', value: '8192 65536 16777216' }
      - { key: 'net.ipv4.udp_wmem_min', value: '16384' }
      - { key: 'net.ipv4.tcp_max_tw_buckets', value: '1440000' }
      - { key: 'net.ipv4.tcp_tw_recycle', value: '1' }
      - { key: 'net.ipv4.tcp_tw_reuse', value: '1' }
    notify:
    - reload sysctl

# FROM: https://easyengine.io/tutorials/linux/sysctl-conf/